name: Check Markdown Links

on:
  schedule:
    - cron: '0 9 * * 1' # Mondays at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
        with:
          submodules: recursive

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # ratchet:lycheeverse/lychee-action@v2
        with:
          args: --config ./lychee.toml './skills/**/*.md' './plugins/**/*.md' './*.md'
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Issue Body
        if: steps.lychee.outputs.exit_code != 0
        run: |
          cat << 'EOF' > ./lychee/issue-body.md
          > **Note:** All broken links need to be updated in the internal source of truth.

          EOF
          cat ./lychee/out.md >> ./lychee/issue-body.md

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # ratchet:peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/issue-body.md
          labels: bug, link checker

      - name: Fail if there were errors
        if: steps.lychee.outputs.exit_code != 0
        run: exit ${{ steps.lychee.outputs.exit_code }}
